language: objective-c

before_install:
  - brew update
  - brew install ant

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"

script: ant -buildfile air/build/build.xml